### ISSUE TITLE
stackoverflow crash

### ISSUE THREAD

**Issue by phit** [kjmaster1/MagicBooks#9]
https://gist.github.com/phit/92700ec80fe302b3fdea469e2ccfe828

**Comment by gabizou** [comment]
To get an excerpt as to what's happening:
This is an issue with how Sponge uses the method `getTileData` from Forge to save tile entities, unfortunately,  MagicBooks is doing some awkward recursion by overriding `getTileData` to instead re-run `writeOnNBT` as can be seen [here](https://github.com/kjmaster1/MagicBooks/blob/7e9fa2f202a1b4d8e72e561434536e2fd8c3cbd4/src/main/java/com/kjmaster/mb/tileentities/crystals/TileEntityWaterCrystal.java#L102). Since this is an unnecessary override for a use case very specific to Sponge (so that it can too write it's own custom data without storing said custom data in extra places), the proper "fix" would be to remove the unnecessary overrides in the tile entities source code for MagicBooks.

Optimally, we'd properly suggest said change in a PR to the repository of the mod with some explanation as above. I can't guarantee I'll be able to get to it too, but @kashike @blood and maybe @Aaron1011 may be able to get to doing said PR sooner than I can.
